# Generated by Django 5.2.7 on 2025-10-20 18:55

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='O telefone deve conter entre 10 e 11 dígitos', regex='^\\d{10,11}$')])),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve ter 11 números.')])),
                ('senha', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='A senha deve conter pelo menos 1 letra maiúscula, 1 número e 1 caractere', regex='^(?=.[A-Z])(?=.\\d)(?=.[@$!%?&])')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
