# Generated by Django 5.2.7 on 2025-10-23 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve ter 11 números.')]),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='senha',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='A senha deve conter pelo menos 1 letra maiúscula, 1 número e 1 caractere', regex='^(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%?&]).+$')]),
        ),
    ]
